### ISSUE TITLE
What account username + Password do I use for this?

### ISSUE THREAD

**Issue by jmherbst** [google/python-laurel#1]
Curious about how to use this package?

**Comment by acoll** [comment]
I used my login info for the C by GE app. I got it to connect and list but I don't have any devices setup yet. I got my bulbs in the mail yesterday and plan on trying it out tonight after work with https://github.com/home-assistant/home-assistant/pull/19176.

**Comment by mjg59** [comment]
Yes, the username and password is the set used with the app - I haven't implemented bulb setup from scratch.
