### ISSUE TITLE
Origin of URL

### ISSUE THREAD

**Issue by jeshall** [google/python-laurel#2]
https://github.com/google/python-laurel/blob/76c703f10a1857dbe0a4cd2ef59f7be03a38efce/laurel/__init__.py#L26

How did you acquire this authentication URL? Who hosts it?

**Comment by mjg59** [comment]
I used https://mitmproxy.org/ and a phone running Android 6. You set up an access point with the proxy and enroll the fake certificate in the phone, and then all API calls that the app makes are recorded by mitmproxy. You can also disassemble the apk with https://github.com/skylot/jadx and look for stuff there. xlink is a Chinese company who provide an IoT management platform, so I assume that GE contract out the cloud service to them.

**Comment by jeshall** [comment]
I love your approach to capturing the requests. I attempted it but used  wireshark and was inundated with packets. Spent most of my energy getting the filters set.
